Update node.js.yaml

diff --git a/.github/workflows/node.js.yaml b/.github/workflows/node.js.yaml
--- a/.github/workflows/node.js.yaml
+++ b/.github/workflows/node.js.yaml
@@ -15,3 +15,26 @@ jobs:
       with:
           name: name-artifact
           path: name.txt
+  release:
+      runs-on: ubuntu-latest
+      permissions:
+        contents: write
+        
+      needs: build
+
+      steps: 
+        - uses: actions/download-artifact@v3
+          with:
+             name: name-artifact
+             path: name.txt
+        - name: List files
+          run: ls -l
+        - name: Read name from artifact
+          run: |
+            if [ -f name.txt ]; then
+              NAME=$(cat name.txt)
+              echo "The name from the artifact is $NAME"
+            else
+              echo "Artifact file not found."
+              exit 1
+            fi
